project:
    trading_home: ${TRADING_HOME:-/Users/laurenthericourt/projets/trading/trading/}
fxcm:
    authentication_key: ${TRADING_FXCM_KEY:-config/secrets/fxcm_secret.txt}
    logs_path: ${TRADING_FXCM_LOGS_PATH:-logs/fxcm.txt}
database:
    host: ${TRADING_DB_HOST:-localhost}
    name: ${TRADING_DB_NAME:-trading}
    port: ${TRADING_DB_PORT:-5700}
    user: ${TRADING_DB_USER:-admin}
    password_path: ${TRADING_DB_PASSWORD_PATH:-config/secrets/postgres_secret.txt}



